---
abstract: 'Create config files for the vr-codebase pipelines'
author:
  - 'Andrew J. Page <ap13@sanger.ac.uk>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-VertRes-Config
requires:
  DBI: 0
  Data::Dumper: 0
  Exception::Class: 0
  File::Basename: 0
  File::Path: 0
  File::Slurp: 0
  Getopt::Long: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
resources:
  homepage: http://www.sanger.ac.uk/
  repository: https://github.com/sanger-pathogens/Bio-VertRes-Config.git
version: 1.133090
